<p style="text-align:center">
    <a href="https://skills.network/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDA0321ENSkillsNetwork928-2022-01-01" target="_blank">
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/assets/logos/SN_web_lightmode.png" width="200" alt="Skills Network Logo"  />
    </a>
</p>

# **Data Wrangling Lab**

Estimated time needed: **45 to 60** minutes

In this assignment you will be performing data wrangling.

## Objectives

In this lab you will perform the following:

-   Identify duplicate values in the dataset.

-   Remove duplicate values from the dataset.

-   Identify missing values in the dataset.

-   Impute the missing values in the dataset.

-   Normalize data in the dataset.

<hr>

## Hands on Lab

Import pandas module.

In [1]:
import pandas as pd
import requests

Load the dataset into a dataframe.

In [11]:
# URL of the CSV file
url = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DA0321EN-SkillsNetwork/LargeData/m1_survey_data.csv"


# Send a GET request to the URL
response = requests.get(url)

# Check if the request was successful (status code 200)
if response.status_code == 200:
    # Save the content of the response to a file
    with open('survey_data.csv', 'wb') as f:
        f.write(response.content)
    
    
    
    print("CSV file downloaded and successfully.")
else:
    print("Failed to download CSV file.")

CSV file downloaded and successfully.

In [12]:
# Read the downloaded CSV file into a pandas DataFrame
df = pd.read_csv('survey_data.csv')

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11552 entries, 0 to 11551
Data columns (total 85 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Respondent              11552 non-null  int64
 1   MainBranch              11552 non-null  object
 2   Hobbyist                11552 non-null  object
 3   OpenSourcer             11552 non-null  object
 4   OpenSource              11471 non-null  object
 5   Employment              11552 non-null  object
 6   Country                 11552 non-null  object
 7   Student                 11499 non-null  object
 8   EdLevel                 11436 non-null  object
 9   UndergradMajor          10812 non-null  object
 10  EduOther                11388 non-null  object
 11  OrgSize                 11454 non-null  object
 12  DevType                 11485 non-null  object
 13  YearsCode               11543 non-null  object
 14  Age1stCode              11539 non-null  object
 15  YearsCodePro            11536 non-null  object
 16  CareerSat               11552 non-null  object
 17  JobSat                  11551 non-null  object
 18  MgrIdiot                11054 non-null  object
 19  MgrMoney                11050 non-null  object
 20  MgrWant                 11054 non-null  object
 21  JobSeek                 11552 non-null  object
 22  LastHireDate            11552 non-null  object
 23  LastInt                 11129 non-null  object
 24  FizzBuzz                11515 non-null  object
 25  JobFactors              11549 non-null  object
 26  ResumeUpdate            11511 non-null  object
 27  CurrencySymbol          11552 non-null  object
 28  CurrencyDesc            11552 non-null  object
 29  CompTotal               10737 non-null  float64
 30  CompFreq                11346 non-null  object
 31  ConvertedComp           10730 non-null  float64
 32  WorkWeekHrs             11427 non-null  float64
 33  WorkPlan                11429 non-null  object
 34  WorkChallenge           11384 non-null  object
 35  WorkRemote              11544 non-null  object
 36  WorkLoc                 11520 non-null  object
 37  ImpSyn                  11547 non-null  object
 38  CodeRev                 11551 non-null  object
 39  CodeRevHrs              9083 non-null   float64
 40  UnitTests               11523 non-null  object
 41  PurchaseHow             11354 non-null  object
 42  PurchaseWhat            11514 non-null  object
 43  LanguageWorkedWith      11541 non-null  object
 44  LanguageDesireNextYear  11415 non-null  object
 45  DatabaseWorkedWith      11096 non-null  object
 46  DatabaseDesireNextYear  10497 non-null  object
 47  PlatformWorkedWith      11130 non-null  object
 48  PlatformDesireNextYear  10991 non-null  object
 49  WebFrameWorkedWith      10139 non-null  object
 50  WebFrameDesireNextYear  9918 non-null   object
 51  MiscTechWorkedWith      9343 non-null   object
 52  MiscTechDesireNextYear  10078 non-null  object
 53  DevEnviron              11523 non-null  object
 54  OpSys                   11518 non-null  object
 55  Containers              11470 non-null  object
 56  BlockchainOrg           9198 non-null   object
 57  BlockchainIs            8915 non-null   object
 58  BetterLife              11452 non-null  object
 59  ITperson                11517 non-null  object
 60  OffOn                   11514 non-null  object
 61  SocialMedia             11251 non-null  object
 62  Extraversion            11532 non-null  object
 63  ScreenName              11039 non-null  object
 64  SOVisit1st              11227 non-null  object
 65  SOVisitFreq             11547 non-null  object
 66  SOVisitTo               11551 non-null  object
 67  SOFindAnswer            11549 non-null  object
 68  SOTimeSaved             11501 non-null  object
 69  SOHowMuchTime           9616 non-null   object
 70  SOAccount               11551 non-null  object
 71  SOPartFreq              10404 non-null  object
 72  SOJobs                  11546 non-null  object
 73  EntTeams                11547 non-null  object
 74  SOComm                  11552 non-null  object
 75  WelcomeChange           11463 non-null  object
 76  SONewContent            9557 non-null   object
 77  Age                     11255 non-null  float64
 78  Gender                  11477 non-null  object
 79  Trans                   11429 non-null  object
 80  Sexuality               11005 non-null  object
 81  Ethnicity               10869 non-null  object
 82  Dependents              11408 non-null  object
 83  SurveyLength            11533 non-null  object
 84  SurveyEase              11538 non-null  object
dtypes: float64(5), int64(1), object(79)
memory usage: 7.5+ MB

In [14]:
df.head()

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,...,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
0,4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelorâ€™s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
1,9,I am a developer by profession,Yes,Once a month or more often,The quality of OSS and closed source software ...,Employed full-time,New Zealand,No,Some college/university study without earning ...,"Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,NaN,23.0,Man,No,Bisexual,White or of European descent,No,Appropriate in length,Neither easy nor difficult
2,13,I am a developer by profession,Yes,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,United States,No,"Masterâ€™s degree (MA, MS, M.Eng., MBA, etc.)","Computer science, computer engineering, or sof...",...,Somewhat more welcome now than last year,Tech articles written by other developers;Cour...,28.0,Man,No,Straight / Heterosexual,White or of European descent,Yes,Appropriate in length,Easy
3,16,I am a developer by profession,Yes,Never,The quality of OSS and closed source software ...,Employed full-time,United Kingdom,No,"Masterâ€™s degree (MA, MS, M.Eng., MBA, etc.)",NaN,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,26.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Neither easy nor difficult
4,17,I am a developer by profession,Yes,Less than once a month but more than once per ...,The quality of OSS and closed source software ...,Employed full-time,Australia,No,"Bachelorâ€™s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,29.0,Man,No,Straight / Heterosexual,Hispanic or Latino/Latina;Multiracial,No,Appropriate in length,Easy

## Finding duplicates

In this section you will identify duplicate values in the dataset.

 Find how many duplicate rows exist in the dataframe.

In [15]:
# your code goes here
num_duplicates = df.duplicated().sum()
num_duplicates

154

In [16]:
df["CompFreq"].duplicated().sum()

11548

## Removing duplicates

Remove the duplicate rows from the dataframe.

In [18]:
# your code goes here
df_wo_duplicates = df.drop_duplicates()
df_wo_duplicates.shape

(11398, 85)

Verify if duplicates were actually dropped.

In [19]:
# your code goes here / same as fnc. duplicated()
print("Number of deleted rows is:",df.shape[0] - df_wo_duplicates.shape[0])

Number of deleted rows is: 154

In [20]:
df_wo_duplicates["CompFreq"].nunique()

3

In [ ]:
df_wo_duplicates[]

## Finding Missing values

Find the missing values for all columns.

In [21]:
import numpy as np

# replace "?" to NaN
df.replace("?", np.nan, inplace = True)
df.head(5)

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,...,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
0,4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelorâ€™s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
1,9,I am a developer by profession,Yes,Once a month or more often,The quality of OSS and closed source software ...,Employed full-time,New Zealand,No,Some college/university study without earning ...,"Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,NaN,23.0,Man,No,Bisexual,White or of European descent,No,Appropriate in length,Neither easy nor difficult
2,13,I am a developer by profession,Yes,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,United States,No,"Masterâ€™s degree (MA, MS, M.Eng., MBA, etc.)","Computer science, computer engineering, or sof...",...,Somewhat more welcome now than last year,Tech articles written by other developers;Cour...,28.0,Man,No,Straight / Heterosexual,White or of European descent,Yes,Appropriate in length,Easy
3,16,I am a developer by profession,Yes,Never,The quality of OSS and closed source software ...,Employed full-time,United Kingdom,No,"Masterâ€™s degree (MA, MS, M.Eng., MBA, etc.)",NaN,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,26.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Neither easy nor difficult
4,17,I am a developer by profession,Yes,Less than once a month but more than once per ...,The quality of OSS and closed source software ...,Employed full-time,Australia,No,"Bachelorâ€™s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,29.0,Man,No,Straight / Heterosexual,Hispanic or Latino/Latina;Multiracial,No,Appropriate in length,Easy

In [13]:
# your code goes here
missing_data = df_wo_duplicates.isnull().sum().sum()
missing_data

30967

Find out how many rows are missing in the column 'WorkLoc'

In [16]:
# your code goes here
df_wo_duplicates["Country"].isnull().sum().sum()

0

## Imputing missing values

Find the  value counts for the column WorkLoc.

In [21]:
# your code goes here
new_df = pd.DataFrame(df_wo_duplicates["UndergradMajor"].value_counts())
new_df

                                                    count
UndergradMajor
Computer science, computer engineering, or soft...   6953
Information systems, information technology, or...    794
Another engineering discipline (ex. civil, elec...    759
Web development or web design                         410
A natural science (ex. biology, chemistry, phys...    403
Mathematics or statistics                             372
A business discipline (ex. accounting, finance,...    244
A social science (ex. anthropology, psychology,...    210
A humanities discipline (ex. literature, histor...    207
Fine arts or performing arts (ex. graphic desig...    161
I never declared a major                              124
A health science (ex. nursing, pharmacy, radiol...     24

Identify the value that is most frequent (majority) in the WorkLoc column.

In [38]:
#make a note of the majority value here, for future reference

df_wo_duplicates["WorkLoc"].value_counts().idxmax()

'Office'

Impute (replace) all the empty rows in the column WorkLoc with the value that you have identified as majority.

In [37]:
# your code goes here
df_wo_missing = df_wo_duplicates["WorkLoc"].replace(np.nan, "Office")

After imputation there should ideally not be any empty rows in the WorkLoc column.

Verify if imputing was successful.

In [ ]:
# your code goes here

## Normalizing data

There are two columns in the dataset that talk about compensation.

One is "CompFreq". This column shows how often a developer is paid (Yearly, Monthly, Weekly).

The other is "CompTotal". This column talks about how much the developer is paid per Year, Month, or Week depending upon his/her "CompFreq". 

This makes it difficult to compare the total compensation of the developers.

In this section you will create a new column called 'NormalizedAnnualCompensation' which contains the 'Annual Compensation' irrespective of the 'CompFreq'.

Once this column is ready, it makes comparison of salaries easy.

<hr>

List out the various categories in the column 'CompFreq'

In [41]:
# your code goes here
df_wo_duplicates["CompFreq"].value_counts()

CompFreq
Yearly     6073
Monthly    4788
Weekly      331
Name: count, dtype: int64

Create a new column named 'NormalizedAnnualCompensation'. Use the hint given below if needed.

Double click to see the **Hint**.

<!--

Use the below logic to arrive at the values for the column NormalizedAnnualCompensation.

If the CompFreq is Yearly then use the exising value in CompTotal
If the CompFreq is Monthly then multiply the value in CompTotal with 12 (months in an year)
If the CompFreq is Weekly then multiply the value in CompTotal with 52 (weeks in an year)

-->

If the CompFreq is Yearly then use the exising value in CompTotal
If the CompFreq is Monthly then multiply the value in CompTotal with 12 (months in an year)
If the CompFreq is Weekly then multiply the value in CompTotal with 52 (weeks in an year)

In [ ]:
# your code goes here
NormalizedAnnualCompensation

df['NormalizedAnnualCompensation'] = df['length']/df['length'].max()

In [26]:
# Vytvorte novÃ½ stÄºpec 'NormalizedAnnualCompensation'
df_wo_duplicates['NormalizedAnnualCompensation'] = df_wo_duplicates['CompTotal']

# Logika na zÃ­skanie hodnÃ´t pre stÄºpec 'NormalizedAnnualCompensation'
# Ak je CompFreq 'Yearly', pouÅ¾ite existujÃºcu hodnotu v CompTotal
# Ak je CompFreq 'Monthly', vynÃ¡sobte hodnotu v CompTotal s 12 (mesiacov v roku)
# Ak je CompFreq 'Weekly', vynÃ¡sobte hodnotu v CompTotal s 52 (tÃ½Å¾dÅˆov v roku)
df_wo_duplicates.loc[df_wo_duplicates['CompFreq'] == 'Monthly', 'NormalizedAnnualCompensation'] *= 12
df_wo_duplicates.loc[df_wo_duplicates['CompFreq'] == 'Weekly', 'NormalizedAnnualCompensation'] *= 52

# Zobrazenie Ãºdajov
df_wo_duplicates[['CompFreq', 'CompTotal', 'NormalizedAnnualCompensation', "ConvertedComp", "CurrencySymbol"]]

C:\Users\jakub\AppData\Local\Temp\ipykernel_20808\1112750479.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_wo_duplicates['NormalizedAnnualCompensation'] = df_wo_duplicates['CompTotal']

,CompFreq,CompTotal,NormalizedAnnualCompensation,ConvertedComp,CurrencySymbol
0,Yearly,61000.0,61000.0,61000.0,USD
1,Yearly,138000.0,138000.0,95179.0,NZD
2,Yearly,90000.0,90000.0,90000.0,USD
3,Monthly,29000.0,348000.0,455352.0,GBP
4,Yearly,90000.0,90000.0,65277.0,AUD
...,...,...,...,...,...
11547,Yearly,130000.0,130000.0,130000.0,USD
11548,Yearly,74400.0,74400.0,19880.0,PLN
11549,Yearly,105000.0,105000.0,105000.0,USD
11550,Yearly,80000.0,80000.0,80371.0,CHF
11551,NaN,NaN,NaN,NaN,GBP

In [25]:
df_wo_duplicates["NormalizedAnnualCompensation"].median()

100000.0

## Authors

Ramesh Sannareddy

### Other Contributors

Rav Ahuja

## Change Log

| Date (YYYY-MM-DD) | Version | Changed By        | Change Description                 |
| ----------------- | ------- | ----------------- | ---------------------------------- |
| 2020-10-17        | 0.1     | Ramesh Sannareddy | Created initial version of the lab |

 Copyright Â© 2020 IBM Corporation. This notebook and its source code are released under the terms of the [MIT License](https://cognitiveclass.ai/mit-license?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDA0321ENSkillsNetwork928-2022-01-01&cm_mmc=Email_Newsletter-_-Developer_Ed%2BTech-_-WW_WW-_-SkillsNetwork-Courses-IBM-DA0321EN-SkillsNetwork-21426264&cm_mmca1=000026UJ&cm_mmca2=10006555&cm_mmca3=M12345678&cvosrc=email.Newsletter.M12345678&cvo_campaign=000026UJ).